name: 🐛 Bug Report
description: Create a bug report to help improve Python-EST
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Python-EST Version
      description: What version of Python-EST are you running?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.9.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on?
      placeholder: "e.g., Ubuntu 20.04, Windows 10, macOS 12.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure EST proxy with...
        2. Send request to...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant parts of your est_proxy.cfg (remove sensitive data)
      render: ini
      placeholder: |
        [Daemon]
        port = 8443
        ...

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (remove sensitive information)
      render: text
      placeholder: Paste log output here...

  - type: checkboxes
    id: terms
    attributes:
      label: Security
      description: Have you checked for sensitive information in this report?
      options:
        - label: I have removed all sensitive information (passwords, private keys, etc.)
          required: true