name: EST protocol tests by using globalsign estclient
on:
  push:
  pull_request:
    branches: [ devel ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  est_proto_globalsign:
    name: "est_proto_gsign"
    runs-on: ubuntu-latest
    steps:
    - name: "checkout GIT"
      uses: actions/checkout@v2

    - name: "[ PREPARE ] Build docker-compose"
      working-directory: examples/Docker/
      run: |
        sudo mkdir -p data
        docker network create est
        docker-compose up -d
        docker-compose logs

    - name: "[ PREPARE ] est-proxy config"
      run: |
        sudo cp .github/wf_data/est_proxy_basic.cfg examples/Docker/data/est_proxy.cfg
        sudo cp -R .github/wf_data/certs examples/Docker/data/
        sudo cp -R .github/wf_data/xca examples/Docker/data/
        sudo chmod 777 examples/Docker/data/est_proxy.cfg
        sudo cat .github/wf_data/est_proxy_clientauth.cfg >> examples/Docker/data/est_proxy.cfg
        sudo cat .github/wf_data/est_proxy_xca.cfg >> examples/Docker/data/est_proxy.cfg
        cd examples/Docker/
        docker-compose restart
        docker-compose logs

    - name: "[ PREPARE ] estclient config"
      run: |
        sudo mkdir /tmp/certs
        sudo chmod -R 777 /tmp/certs
        sudo cp .github/wf_data/certs/cacerts.pem /tmp/certs
        sudo cp .github/wf_data/certs/est*.pem /tmp/certs
        (umask 000; openssl genrsa 4096 > /tmp/certs/4096.pem)
        (umask 000; openssl genrsa 2048 > /tmp/certs/2048.pem)

    - name: "[ Test ] generate csr(s) "
      run: |
        docker run -v /tmp/certs:/tmp/certs --network est grindsa/estclient estclient.globalsign csr -key /tmp/certs/2048.pem -cn 'est-clt-2048' -out /tmp/certs/csr2048.pem
        docker run -v /tmp/certs:/tmp/certs --network est grindsa/estclient estclient.globalsign csr -key /tmp/certs/4096.pem -cn 'est-clt-4096' -out /tmp/certs/csr4096.pem
        sudo ls -la /tmp/certs

    - name: "[ Test ] fetch Ca certificates using estclient"
      run: |
        docker run -v /tmp/certs:/tmp/certs --network est grindsa/estclient estclient.globalsign cacerts -server est-proxy.est:17443 -insecure -out /tmp/_cacerts.pem

    - name: "[ Test ] enroll certificate 2048 using estclient"
      run: |
        docker run -v /tmp/certs:/tmp/certs --network est grindsa/estclient estclient.globalsign enroll -server est-proxy.est:17443 -explicit /tmp/certs/cacerts.pem -csr /tmp/certs/csr2048.pem -out /tmp/certs/cert-2048.pem -certs /tmp/certs/estclient.crt.pem -key /tmp/certs/estclient.key.pem
        sudo openssl x509 -outform der -in /tmp/certs/cert-2048.pem -out /tmp/certs/cert-2048.der
        sudo ls -la /tmp/certs

    - name: "[ Test ] reenroll certificate 2048 using estclient"
      run: |
        docker run -v /tmp/certs:/tmp/certs --network est grindsa/estclient estclient.globalsign reenroll -server est-proxy.est:17443 -explicit /tmp/certs/cacerts.pem -out /tmp/certs/cert-2048-new.pem -certs /tmp/certs/cert-2048.pem -key /tmp/certs/2048.pem
        sudo openssl x509 -outform der -in /tmp/certs/cert-2048-new.pem  -out /tmp/certs/cert-2048-new.der
        sudo ls -la /tmp/certs

    - name: "[ Test ] enroll certificate 4096 using estclient"
      run: |
        docker run -v /tmp/certs:/tmp/certs --network est grindsa/estclient estclient.globalsign enroll -server est-proxy.est:17443 -explicit /tmp/certs/cacerts.pem -csr /tmp/certs/csr4096.pem -out /tmp/certs/cert-4096.pem -certs /tmp/certs/estclient.crt.pem -key /tmp/certs/estclient.key.pem
        sudo openssl x509 -outform der -in /tmp/certs/cert-4096.pem -out /tmp/certs/cert-4096.der
        sudo ls -la /tmp/certs

    - name: "[ Test ] reenroll certificate 4096 using estclient"
      run: |
        docker run -v /tmp/certs:/tmp/certs --network est grindsa/estclient estclient.globalsign reenroll -server est-proxy.est:17443 -explicit /tmp/certs/cacerts.pem -out /tmp/certs/cert-4096-new.pem -certs /tmp/certs/cert-4096.pem -key /tmp/certs/4096.pem
        sudo openssl x509 -outform der -in /tmp/certs/cert-4096-new.pem -out /tmp/certs/cert-4096-new.der
        sudo ls -la /tmp/certs

    - name: "[ * ] collecting test logs"
      if: ${{ failure() }}
      run: |
        mkdir -p ${{ github.workspace }}/artifact/upload
        sudo cp -rp examples/Docker/data/ ${{ github.workspace }}/artifact/data/
        sudo cp -rp /tmp/certs ${{ github.workspace }}/artifact/data/tmp_certs
        cd examples/Docker
        docker-compose logs > ${{ github.workspace }}/artifact/docker-compose.log
        sudo tar -C ${{ github.workspace }}/artifact/ -cvzf ${{ github.workspace }}/artifact/upload/artifact.tar.gz docker-compose.log data

    - name: "[ * ] uploading artificates"
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: est_proto_curl.tar.gz
        path: ${{ github.workspace }}/artifact/upload/
