# workflow to check the est-proxy document package for consistency

name: Markdown check

on:
  push:
  pull_request:
    branches: [ devel ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    - name: Lint changelog file root
      uses: avto-dev/markdown-lint@v1
      with:
        args: '*.md'
    - name: Lint changelog file docs
      uses: avto-dev/markdown-lint@v1
      with:
        args: './docs/*.md'
    #- name: Lint changelog file docker
    #  uses: avto-dev/markdown-lint@v1
    #  with:
    #    args: './examples/Docker/*.md'
